#!/bin/sh

APP=gimp
mkdir tmp;
cd tmp;

# DOWNLOADING THE DEPENDENCIES
wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-i686.AppImage -O appimagetool
wget https://github.com/ivan-hc/pkg2appimage-32bit/releases/download/continuous/pkg2appimage-i386.AppImage -O pkg2appimage
chmod a+x ./appimagetool ./pkg2appimage

# CREATING THE APPIMAGE
echo "app: gimp
binpatch: true

ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu bionic-security main universe restricted multiverse
    - deb http://archive.ubuntu.com/ubuntu/ bionic-updates main universe restricted multiverse
  ppas:
    - savoury1/ffmpeg4
    - savoury1/gimp
    - savoury1/graphics
    - savoury1/multimedia
    - savoury1/build-tools
    - savoury1/backports
  packages:
    - gimp
    - gimp-data
    - gimp-data-extras
    - gimp-help-common" >> recipe.yml;

./pkg2appimage ./recipe.yml;

rm -R -f ./$APP/$APP.AppDir/AppRun
wget https://raw.githubusercontent.com/ivan-hc/GIMP-appimage/main/AppRun -P ./$APP/$APP.AppDir/
chmod a+x ./$APP/$APP.AppDir/AppRun

ARCH=i386 ./appimagetool -n ./$APP/$APP.AppDir
cd ..
mv ./tmp/*.AppImage ./$APP
chmod a+x ./$APP
rm -R -f ./tmp
